spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: spring.datasource.url=jdbc:postgresql://ec2-52-201-55-4.compute-1.amazonaws.com/5432/devudehtks2c3v?sslmode=require
    username: iwhpvuwlbkhrtg
    password: bd2b6d685be4b7e0330470209bf6c0f7a0fd951e64f5f29b15f29e58342ae3b6
  mail:
    host: smtp.gmail.com
    port: 587
    username: rakus.yahoo@gmail.com
    password: lggfscuvpevplvsw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
#spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/ramen_record
#    username: higashiiida
#    password: postgres
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: rakus.yahoo@gmail.com
#    password: Rakus!!tennis
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#  servlet:
#    multipart:
#      max-file-size: 30MB
#      max-request-size: 30MB